version: "3.9"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 24672:24672
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - api

  frontend:
    image: node:alpine
    container_name: frontend
    command: npm run dev
    restart: always
    working_dir: /frontend
    environment:
      PORT: 80
      HOST: 0.0.0.0
      NODE_ENV: "development"

  api:
    image: node:alpine
    container_name: api
    command: npm run dev
    working_dir: /api
    depends_on:
      - database
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PGPASSWORD: ${DATABASE_PASSWORD}

  pipeline:
    image: node:alpine
    container_name: pipeline
    command: npm run dev
    working_dir: /pipeline
    depends_on:
      - database
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PGPASSWORD: ${DATABASE_PASSWORD}

  database:
    image: postgres:15.3-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data/database:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    container_name: cache
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./data/cache:/data