services:
  automated-playlists-nginx:
    ports:
      - 8000:8000

  automated-playlists-frontend:
    command: npm run dev
    environment:
      NODE_ENV: development

  automated-playlists-backend:
    command: npm run dev
    environment:
      NODE_ENV: development