services:
  automated-playlists-nginx:
    ports:
      - 8000:8000

  automated-playlists-frontend:
    command: npm run deploy

  automated-playlists-backend:
    command: npm run deploy
    environment:
      NODE_ENV: production