services:
  automated-playlists-nginx:
    ports:
      - 8080:8080
      - 24672:24672

  automated-playlists-frontend:
    command: npm run dev
    environment:
      NODE_ENV: development

  automated-playlists-backend:
    command: npm run dev
    environment:
      NODE_ENV: development